### ISSUE TITLE
Unknow command

### ISSUE THREAD

**Issue by lsamain** [AlexanderLindsay/PodcastPlayerBot#1]
Hi,

Your projet is very interesting. I follow your tutorial step by step
When I put the command "$pod help", it works: the bot prints the commands.
But, when I try the "$pod add feed aliceisntdead http://aliceisntdead.libsyn.com/rss", error : "Unknown command.".
I try too : "$pod add aliceisntdead http://aliceisntdead.libsyn.com/rss", but I have still an error. 

Thanks

**Comment by AlexanderLindsay** [comment]
That is because I changed the command structure when I updated the project and forgot to update the readme. Sorry about that.

The command to add feeds is now: `$pod rss add aliceisntdead http://aliceisntdead.libsyn.com/rss`

Let me know if that works and I will work on fixing the readme.

**Comment by lsamain** [comment]
With your commands, I don't have any error now but it don't work :
When I write "$pod rss list" just after, the answer of the bot is : "No feeds" :/
And the folder that I have defined in secret.cfg, (feedFile) is empty

Have you any ideas? And can you give me all the new commands please? 

Thank you !

**Comment by AlexanderLindsay** [comment]
The config file should be `secrets.config`, unless you have modified the app.config to point to your config. Also the `feedFile` setting should be in the `appSettings` section of the `secrets.config` file.

Let me know if that helps.

Here is the output of help, except I added the rss group name (which is missing in the actual bot response and I should fix it at some point):
```
------------------------------
info
displays information about the bot
------------------------------
help
displays commands
------------------------------
play url
plays a podcast in the voice channel you are currently in
url required: The url to play
------------------------------
stop
halts the playing of the podcast
------------------------------
leave
the bot will leave the voice channel it is currently in
------------------------------
rss add
adds a rss feed url to the bot
name required: The name to give the feed
url required: The url of the rss feed
------------------------------
rss info
displays information about an rss feed
name required: The name of the feed
------------------------------
rss list
lists rss feeds
------------------------------
rss episodes
lists episodes in an rss feed
name required: The name of the feed
------------------------------
rss what
provides information on the currenly playing episode
------------------------------
rss play last
plays the last episode of the given rss feed
name required: The name of the feed
------------------------------
rss play next
plays the next episode of the given rss feed
name required: The name of the feed
------------------------------
rss play
play the given episode of the given rss feed
name required: The name of the feed
episodeNumber required: The episode number
------------------------------
rss restart
restarts the currently playing episode
------------------------------
```

**Comment by AlexanderLindsay** [comment]
@lsamain Did that solve the issue?
