### ISSUE TITLE
Bot stopped working recently

### ISSUE THREAD

**Issue by CraigUK37** [AlexanderLindsay/PodcastPlayerBot#4]
Not sure if its due to the update to discord with the channel categories or not, but the bot has stopped working for me.  

I get, in red text, the following message.

[Gateway] Error handling Dispatch (GUILD_AVAILABLE): Unknown guild channel type

Followed by others.

The bot is set as away, not online, and will respond in private messages to commands like $pod help, but is unresponsive in the actual discord channel. 
[Image of errors](https://i.imgur.com/z1ZSRjT.png)

**Comment by AlexanderLindsay** [comment]
Ok, I will take a look. You are probably correct about the recent Discord update causing it, that would make sense.

**Comment by AlexanderLindsay** [comment]
Ok, I updated it to the latest nuget package of https://github.com/RogueException/Discord.Net and it is able to connect again.
